### PR TITLE
fixed array check

### PR DESCRIPTION
**Pull request by dmikel**
causes problems on GWT usage

### CODE REVIEW

**Comment by davidjgraph** [comment]
Sorry, but this is valid JavaScript. If a third-party tool cannot support valid JavaScript, the tool is broken.

**Comment by dmikel** [comment]
"1" instanceof String also valid JavaScript but returns false

**Comment by davidjgraph** [comment]
So you're saying `roots instanceof Array` returns false if roots is an Array?

**Comment by dmikel** [comment]
yes, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/instanceof

**Comment by davidjgraph** [comment]
I'm reading the "Not an instanceof" section at the bottom. 

To test if an object is not an instanceof a specific constructor, you can do

if (!(mycar instanceof Car)) {
  // Do something, like:
  // mycar = new Car(mycar)
}

Doesn't that agree with our original code?

**Comment by dmikel** [comment]
I call execute from native method
@com.mxgraph.gwt.client.util.WrapperUtils::unwrap(Lcom/mxgraph/gwt/client/IJavaScriptWrapper;)(this).execute(parentJS, rootsJS)

if i check rootsJS instanceof Array in console on this line it returns true, but in your library roots instanceof Array already false and no any steps between.

from link:
instanceof and multiple context (e.g. frames or windows)
Different scopes have different execution environments. This means that they have different built-ins (different global object, different constructors, etc.). This may result in unexpected results. For instance, [] instanceof window.frames[0].Array will return false, because Array.prototype !== window.frames[0].Array and arrays inherit from the former.

This may not make sense at first, but for scripts dealing with multiple frames or windows, and passing objects from one context to another via functions, this will be a valid and strong issue. For instance, you can securely check if a given object is, in fact, an Array using Array.isArray(myObj)

**Comment by davidjgraph** [comment]
The code is valid JavaScript and performs correctly in native JavaScript. The bug is in GWT, you haven't proved otherwise.

**Comment by davidjgraph** [comment]
isArray is also an ES5 method, our baseline is ES3. We can't change this until we move to ES5.

**Comment by dmikel** [comment]
it's a pity (

you can try:

<script type="text/javascript">
		var newIframe = document.createElement('iframe');
		newIframe.width = '200';newIframe.height = '200';
		newIframe.src = 'about:blank'; 
		document.body.appendChild(newIframe);

		var myContent = '<!DOCTYPE html>'
    + '<html><head><title>My dynamic document</title></head><body>'
    + '<script type="text/javascript"> a = new Array() <\/script>'
    +'</body></html>';

		newIframe.contentWindow.document.open('text/htmlreplace');
		newIframe.contentWindow.document.write(myContent);
		newIframe.contentWindow.document.close();

		alert(window.frames[0].frameElement.contentWindow.a instanceof Array);
	</script>

**Comment by davidjgraph** [comment]
It's not related to GWT, but it's also not the code we're using. It's all very well building an example that fails, but show me how our line of code fails in a JavaScript, then at least we can class it as a bug.

**Comment by dmikel** [comment]
em..
this line shows it:
alert(window.frames[0].frameElement.contentWindow.a instanceof Array);
here is false
if send roots which i received from other frame your check will fail 

for ES3 you can check it like 
Object.prototype.toString.call(roots) == '[object Array]'

**Comment by davidjgraph** [comment]
But why would you reasonably run the layout in another iFrame? This is really bad practice at a coding level, I just don't see why anyone would write such code in a normal situation.

**Comment by dmikel** [comment]
ajax can be done with iframes, GWT uses iframes(maybe they don't know about good practice :) )
not sure what is problem to check it in more right way

but ok - no means no

**Comment by davidjgraph** [comment]
Well, if our baseline were ES5, it's not a big change. But the argument seems to be IE 6-8 vs GWT support. Given we've always supported IE 6-8, it doesn't seem fair to drop that suddenly for GWT.

I'm afraid you're the only person I've heard mention GWT for about 7 years, I really thought the project was dead.

**Pull request closed without merging**
