### PR TITLE
npm build issues.

### LINKED ISSUE #83: mxgraph 3.7.3 fails to install using npm
npm install of mxgraph 3.7.3 fails during 'grunt build' in the postinstall. The error output is shown below.

The problem is that in the 3.7.3 release the javascript shipped under `javascript/src/js` is one big mxClient.js file instead of the individual files used in previous releases. The postinstall script runs `grunt build` which loads Gruntfile.js and tries to merge all of the javascript files into one file (dist/build.js) with a factory function to load it and export it . Line 14 of Gruntfile.js looks for the mxClient.include pattern in `javascript/src/js/mxClient.js` but doesn't find any and then tries to call `map` on `undefined` because the regular expression does not match anything.

My workaround for now is to stick with version 3.7.2-2 as my code relies on the factory that the grunt build wraps around the mxgraph javscript.

```
> mxgraph@3.7.3 postinstall c:\dev\mx\mxweb\node_modules\mxgraph
> grunt build

Loading "Gruntfile.js" tasks...ERROR
>> TypeError: Cannot read property 'map' of null
Warning: Task "build" not found. Use --force to continue.

Aborted due to warnings.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\
fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":
"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! code ELIFECYCLE
npm ERR! errno 3
npm ERR! mxgraph@3.7.3 postinstall: `grunt build`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the mxgraph@3.7.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

### PR DESCRIPTION
**Pull request by NicCOConnor**
Fixes #83 and #102 provided individual source files `javascript/src/js` are present instead of a single minified mxClient.js file when publishing to npm, also allows an npm install directly from the source.

### CODE REVIEW

**Comment by fingerartur** [comment]
this doesn't help, unless I'm missing something. After running `npm install --save git+https://github.com/NicCOConnor/mxgraph.git` I get:

`$ npm install --save git+https://github.com/NicCOConnor/mxgraph.git
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> mxgraph@3.7.5 postinstall C:\Users\Artur\Documents\web\sites\dipl\research\angular\node_modules\mxgraph
> grunt build --base "$(npm prefix)" --gruntfile etc/build/Gruntfile.js

C:\Users\Artur\Documents\web\sites\dipl\research\angular\node_modules\grunt\lib\grunt\task.js:434
    process.chdir(grunt.option('base') || path.dirname(gruntfile));
            ^

Error: ENOENT: no such file or directory, uv_chdir
  at Error (native)
  at Task.task.init (C:\Users\Artur\Documents\web\sites\dipl\research\angular\node_modules\grunt\lib\grunt\task.js:434:13)
  at Object.grunt.tasks (C:\Users\Artur\Documents\web\sites\dipl\research\angular\node_modules\grunt\lib\grunt.js:111:8)
  at Object.module.exports [as cli] (C:\Users\Artur\Documents\web\sites\dipl\research\angular\node_modules\grunt\lib\grunt\cli.js:27:9)
  at Object.<anonymous> (C:\Users\Artur\Documents\web\sites\dipl\research\angular\node_modules\grunt\node_modules\grunt-cli\bin\grunt:44:20)
  at Module._compile (module.js:570:32)
  at Object.Module._extensions..js (module.js:579:10)
  at Module.load (module.js:487:32)
  at tryModuleLoad (module.js:446:12)
  at Function.Module._load (module.js:438:3)
  at Module.require (module.js:497:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (C:\Users\Artur\Documents\web\sites\dipl\research\angular\node_modules\grunt\bin\grunt:3:1)
  at Module._compile (module.js:570:32)
  at Object.Module._extensions..js (module.js:579:10)
  at Module.load (module.js:487:32)
  at tryModuleLoad (module.js:446:12)
  at Function.Module._load (module.js:438:3)
  at Module.runMain (module.js:604:10)
  at run (bootstrap_node.js:394:7)
  at startup (bootstrap_node.js:149:9)
  at bootstrap_node.js:509:3

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN grunt-webpack@2.0.1 requires a peer of webpack@^2.1.0-beta || ^2.2.0-rc || ^2.0.0 but none was installed.
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "git+https://github.com/NicCOConnor/mxgraph.git"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! mxgraph@3.7.5 postinstall: `grunt build --base "$(npm prefix)" --gruntfile etc/build/Gruntfile.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mxgraph@3.7.5 postinstall script 'grunt build --base "$(npm prefix)" --gruntfile etc/build/Gruntfile.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mxgraph package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt build --base "$(npm prefix)" --gruntfile etc/build/Gruntfile.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mxgraph
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mxgraph
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Artur\Documents\web\sites\dipl\research\angular\npm-debug.log
`

**Comment by fingerartur** [comment]
I can now say with certainty that @NicCOConnor 's fix doesn't work on Windows. Luckily I have found a workaround to that.

1.  npm install --save --ignore-scripts git+https://github.com/NicCOConnor/mxgraph.git
2.  in node_modules/mxgraph/package.json replace \"$(npm dir)\" with .
3.  cd node_modules/mxgraph; npm run postinstall;
    (this fixed the first bug, which is a grunt error)

4. create file mxwrapper.ts:
>     import * as mx from 'mxgraph';
>     export const Mx = mx();
    (this fixed the second bug, which is an error in the implementation of AMD/UMD)

Example of how to use mxgraph now:
> import {Mx} from './mxwrapper.ts';
> Mx.mxClient.isBrowserSupported();

**Comment by aputhin** [comment]
Well, on Linux it does work (Ubuntu GNOME 17.04, Node v8.8.1 and NPM 5.4.2). Thanks for the fix @NicCOConnor 

@davidjgraph any ETA on evaluating this, please? :)

**Comment by davidjgraph** [comment]
Did I merge that correctly?

**Comment by NicCOConnor** [comment]
@davidjgraph that works for me both source install and npm install! I'm unsure what's going on with the windows machines. Also, the version is stated at 3.7.5 which was the last time I merged the code, before submitting the PR.  the build.js files states updated code @ 3.8.0 so you probably just need to change the version in the package.json.

**Comment by davidjgraph** [comment]
The Github repo isn't the master repo, sorry, I thought I mentioned that. The master repo will need the build script to automatically create the package.json and output the files to Github. I'm not going to have time to look in the next year, so I've posted a job for a contractor to look, https://www.upwork.com/ab/applicants/939177457659371520/job-details. Anyone interested, just get in touch.

**Comment by nigel-daniels** [comment]
Hi @davidjgraph I just tried installing the latest build but got the same issue (This is on MacOS 10.13.2 using npm 5.6.0)  The error is in the grunt build task still :(

> mxgraph@3.8.0 postinstall /Users/Nigel/git/mxtest/client/js/node_modules/mxgraph
> grunt build

Loading "Gruntfile.js" tasks...ERROR
>> TypeError: Cannot read property 'map' of null
Warning: Task "build" not found. Use --force to continue.

**Comment by aputhin** [comment]
Well, if I got that correctly, you have to run this build script to output it to another repo, which is the one that is used by NPM for publishing? Can't you just publish the new version to NPM?

Sorry to bother you, but while you still can, I hope you can at least fix this NPM build so we can import mxClient the right way into our projects :)

**Comment by NicCOConnor** [comment]
Sorry, I gave bad information above it works with a source install from github `npm install git+https://github.com/jgraph/mxgraph.git --save` it does not work from the npm repo's `npm install mxgraph --save` that package was updated a week ago with the release of 3.8.0 the published npm package. The gruntfile.js will need to be updated in the original repo and republished.

**Comment by nigel-daniels** [comment]
@NicCOConnor sorry I missed that nuance!  To use this package with docker or much else the regular npm install really needs to work.

**Comment by NicCOConnor** [comment]
I'm unsure why docker wouldn't work with a source install it's the same command. you're just changing the location in which you retrive the files. if you need this to work today the solution is above. if you need this to work from the npm repos. You'll have to wait till the devs have time to integrate it into thier primary repo.

**Comment by nigel-daniels** [comment]
@NicCOConnor docker will work but then it leads to a more complex script, it's simpler to have everything in the `package.json` and just call `npm install` when building the environment.  I'm happy to use the workaround for dev, in the longer run a working `npm install` will help.

**Comment by NicCOConnor** [comment]
the point of the --save option is to save it to your package.json file this is what my package.json file looks like after running the command above. 
```
"dependencies": {
    "mxgraph": "git+https://github.com/NicCOConnor/mxgraph.git",
  },
```
in fact, if this line is in your package.json an `npm install mxgraph` does work as well as installing all packages `npm install`

**Comment by nigel-daniels** [comment]
Ok maybe I'm misunderstanding something, I thought the above installs the source not the distributable?  As there is a build step breaking I was assuming we need the distributable version for a production build.

**Comment by nigel-daniels** [comment]
I'm seeing errors when trying the source install too, there still seems to be a grunt based problem.  Here is what I see:

```
$ npm install git+https://github.com/jgraph/mxgraph.git --save
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> fsevents@1.1.3 install /Users/Nigel/git/test/node_modules/fsevents
> node install

[fsevents] Success: "/Users/Nigel/git/test/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> mxgraph@3.8.0 postinstall /Users/Nigel/git/test/node_modules/mxgraph
> grunt build --base "$(npm prefix)" --gruntfile etc/build/Gruntfile.js

Loading "Gruntfile.js" tasks...ERROR
>> TypeError: Cannot read property 'grunt-contrib-concat' of undefined
Warning: Task "build" not found. Use --force to continue.

Aborted due to warnings.
npm ERR! code ELIFECYCLE
npm ERR! errno 3
npm ERR! mxgraph@3.8.0 postinstall: `grunt build --base "$(npm prefix)" --gruntfile etc/build/Gruntfile.js`
npm ERR! Exit status 3
npm ERR! 
npm ERR! Failed at the mxgraph@3.8.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Nigel/.npm/_logs/2017-12-22T22_47_27_095Z-debug.log
```

Any suggestions on what the issue is?

**Comment by tischsoic** [comment]
@nigel-daniels Solution from this comment:
 [https://github.com/jgraph/mxgraph/issues/73#issuecomment-299345090](url)
seems to solve this problem.

I changed this line:
`require(parentFolderName === "node_modules" ? "load-grunt-parent-tasks" : "load-grunt-tasks")(grunt, {scope: 'dependencies'});`

in file etc/build/Gruntfile.js in my forked repository and set it as module, like mentioned before:
`"dependencies": {
    "mxgraph": "git+https://github.com/jgraph/mxgraph.git",
  },`
and it finally worked out. :)

**Comment by become-iron** [comment]
@tischsoic, I just tried your solution under Windows 7 and unfortunately it seems non-working for me.
I put this line `"mxgraph": "git+https://github.com/tischsoic/mxgraph.git",` in package.json, then run `npm install`

Fragment from complete log of run:
```
3112 verbose stack Error: mxgraph@3.8.0 postinstall: `grunt build --base "$(npm prefix)" --gruntfile etc/build/Gruntfile.js`
3112 verbose stack Exit status 1
3112 verbose stack     at EventEmitter.<anonymous> (C:\Users\PC\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
3112 verbose stack     at emitTwo (events.js:125:13)
3112 verbose stack     at EventEmitter.emit (events.js:213:7)
3112 verbose stack     at ChildProcess.<anonymous> (C:\Users\PC\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
3112 verbose stack     at emitTwo (events.js:125:13)
3112 verbose stack     at ChildProcess.emit (events.js:213:7)
3112 verbose stack     at maybeClose (internal/child_process.js:927:16)
3112 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
3113 verbose pkgid mxgraph@3.8.0
3114 verbose cwd D:\Programming\Web\vasily-web-eda
3115 verbose Windows_NT 6.1.7601
3116 verbose argv "D:\\Programming\\Programs\\nodejs\\node.exe" "C:\\Users\\PC\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
3117 verbose node v8.5.0
3118 verbose npm  v5.4.2
3119 error code ELIFECYCLE
3120 error errno 1
3121 error mxgraph@3.8.0 postinstall: `grunt build --base "$(npm prefix)" --gruntfile etc/build/Gruntfile.js`
3121 error Exit status 1
3122 error Failed at the mxgraph@3.8.0 postinstall script.
3122 error This is probably not a problem with npm. There is likely additional logging output above.
3123 verbose exit [ 1, true ]
```

**Comment by tischsoic** [comment]
@become-iron What version of Node.js do you have?
In my case I have run it under Ubuntu and I had Node.js version 8.9.3 installed.

**Comment by become-iron** [comment]
@tischsoic I have Node.js 8.9.4. Under Ubuntu I also can build package. It seems it's OS-specific problem

I just tried to build package under Ubuntu, then copied it in node_modules directory in Windows-located project. Yeah, it's weird. Then imported package like this:
```
let mxgraph = require('mxgraph')({
  mxImageBasePath: './javascript/src/images',
  mxBasePath: './javascript/src'
})
```
So I have next error in console now:
`TypeError: this.createUndoableEdit is not a function`
 
My code:
```js
let mxgraph = require('mxgraph')({
  mxImageBasePath: './javascript/src/images',
  mxBasePath: './javascript/src'
})

let container = document.getElementById('graph')
let model = mxgraph.mxGraphModel()
let graph = new mxgraph.mxGraph(container, model)
```

**Pull request merged**
